# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Information.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from CustomerData import CustomerData


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(500, 500)
        Frame.setMinimumSize(QtCore.QSize(500, 500))
        Frame.setMaximumSize(QtCore.QSize(500, 500))
        Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 501, 500))
        self.label.setStyleSheet("background-image: url(image/Display.jpg);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 481, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"Perpetua Titling MT\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(20, 50, 461, 401))
        self.frame.setStyleSheet("background-color: rgb(0, 36, 66);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 151, 381))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(160, 10, 5, 392))
        self.line.setMinimumSize(QtCore.QSize(5, 0))
        self.line.setMaximumSize(QtCore.QSize(5, 16777215))
        self.line.setBaseSize(QtCore.QSize(5, 0))
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setLineWidth(10)
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(170, 10, 281, 381))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.status = QtWidgets.QLabel(self.frame_3)
        self.status.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.status.setText("")
        self.status.setObjectName("status")
        self.verticalLayout_2.addWidget(self.status)
        self.name = QtWidgets.QLabel(self.frame_3)
        self.name.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.name.setText("")
        self.name.setObjectName("name")
        self.verticalLayout_2.addWidget(self.name)
        self.birthday = QtWidgets.QLabel(self.frame_3)
        self.birthday.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.birthday.setText("")
        self.birthday.setObjectName("birthday")
        self.verticalLayout_2.addWidget(self.birthday)
        self.contact = QtWidgets.QLabel(self.frame_3)
        self.contact.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.contact.setText("")
        self.contact.setObjectName("contact")
        self.verticalLayout_2.addWidget(self.contact)
        self.address = QtWidgets.QLabel(self.frame_3)
        self.address.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.address.setText("")
        self.address.setObjectName("address")
        self.verticalLayout_2.addWidget(self.address)
        self.productName = QtWidgets.QLabel(self.frame_3)
        self.productName.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.productName.setText("")
        self.productName.setObjectName("productName")
        self.verticalLayout_2.addWidget(self.productName)
        self.category = QtWidgets.QLabel(self.frame_3)
        self.category.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.category.setText("")
        self.category.setObjectName("category")
        self.verticalLayout_2.addWidget(self.category)
        self.quantity = QtWidgets.QLabel(self.frame_3)
        self.quantity.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.quantity.setText("")
        self.quantity.setObjectName("quantity")
        self.verticalLayout_2.addWidget(self.quantity)
        self.totalPayment = QtWidgets.QLabel(self.frame_3)
        self.totalPayment.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.totalPayment.setText("")
        self.totalPayment.setObjectName("totalPayment")
        self.verticalLayout_2.addWidget(self.totalPayment)
        self.received = QtWidgets.QLabel(self.frame_3)
        self.received.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.received.setText("")
        self.received.setObjectName("received")
        self.verticalLayout_2.addWidget(self.received)
        self.balance = QtWidgets.QLabel(self.frame_3)
        self.balance.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.balance.setText("")
        self.balance.setObjectName("balance")
        self.verticalLayout_2.addWidget(self.balance)
        self.change = QtWidgets.QLabel(self.frame_3)
        self.change.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.change.setText("")
        self.change.setObjectName("change")
        self.verticalLayout_2.addWidget(self.change)
        self.date = QtWidgets.QLabel(self.frame_3)
        self.date.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.date.setText("")
        self.date.setObjectName("date")
        self.verticalLayout_2.addWidget(self.date)
        self.pushButton_4 = QtWidgets.QPushButton(Frame)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 450, 101, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(51, 51, 51);\n"
"font: 75 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

        self.pushButton_4.clicked.connect(self.minimize)
    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Information"))
        self.label_3.setText(_translate("Frame", "Informations"))
        self.label_2.setText(_translate("Frame", "STATUS"))
        self.label_4.setText(_translate("Frame", "NAME                      :"))
        self.label_5.setText(_translate("Frame", "BIRTHDAY             : "))
        self.label_6.setText(_translate("Frame", "CONTACT NO.        :"))
        self.label_7.setText(_translate("Frame", "ADDRESS                :"))
        self.label_8.setText(_translate("Frame", "PRODUCT               :"))
        self.label_9.setText(_translate("Frame", "CATEGORY             :"))
        self.label_10.setText(_translate("Frame", "QUANTITY              :"))
        self.label_11.setText(_translate("Frame", "TOTAL PAYMENT   :"))
        self.label_12.setText(_translate("Frame", "RECEIVED               :"))
        self.label_13.setText(_translate("Frame", "BALANCE                 :"))
        self.label_23.setText(_translate("Frame", "CHANGE                  :"))
        self.label_24.setText(_translate("Frame", "DATE                        :"))
        self.pushButton_4.setText(_translate("Frame", "OK"))

    def display_customer_data_window(self, data):
        app = QtWidgets.QApplication([])
        window = QtWidgets.QMainWindow()
        ui = Ui_Frame()
        ui.setupUi(window)

        self.status.setText("Status: " + data.getStatus())
        self.name.setText("Name: " + data.getName())
        self.birthday.setText("Birthday: " + data.getBirthday())
        self.contact.setText("Contact Number: " + data.getContactNumber())
        self.address.setText("Address: " + data.getAddress())
        self.category.setText("Category: " + data.getCategory())
        self.productName.setText("Product Name: " + data.getProductName())
        self.quantity.setText("Quantity: " + str(data.getQuantity()))
        self.totalPayment.setText("Total Payment: " + str(data.getTotalPayment()))
        self.received.setText("Payment Received: " + str(data.getPaymentReceived()))
        self.balance.setText("Balance: " + str(data.getBalance()))
        self.change.setText("Change: " + str(data.getChange()))

    def minimize(self):
        Frame.destroy()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
