# -*- coding: utf-8 -*-
import os
import subprocess

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main(object):

    def setupUi(self, main):
        main.setObjectName("main")
        main.setEnabled(True)
        main.resize(800, 500)
        main.setMinimumSize(QtCore.QSize(800, 500))
        main.setMaximumSize(QtCore.QSize(800, 500))
        main.setAutoFillBackground(False)
        self.label = QtWidgets.QLabel(main)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setStyleSheet("background-image: url(image/BG.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(main)
        self.frame.setGeometry(QtCore.QRect(10, 110, 300, 160))
        self.frame.setMinimumSize(QtCore.QSize(300, 160))
        self.frame.setMaximumSize(QtCore.QSize(300, 160))
        self.frame.setStyleSheet("background-color: rgb(0, 36, 66);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_3.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_4.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_4.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_2 = QtWidgets.QPushButton(main)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
                                        "color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Tahoma\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(main)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 781, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"Perpetua Titling MT\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(main)
        self.frame_2.setGeometry(QtCore.QRect(320, 110, 210, 160))
        self.frame_2.setMinimumSize(QtCore.QSize(210, 160))
        self.frame_2.setMaximumSize(QtCore.QSize(210, 160))
        self.frame_2.setStyleSheet("background-color: rgb(0, 36, 66);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_5.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_5.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Tahoma\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(main)
        self.frame_3.setGeometry(QtCore.QRect(540, 110, 250, 160))
        self.frame_3.setMinimumSize(QtCore.QSize(250, 160))
        self.frame_3.setMaximumSize(QtCore.QSize(250, 160))
        self.frame_3.setStyleSheet("background-color: rgb(0, 36, 66);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_6.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_6.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_8.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_8.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Tahoma\";")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_4 = QtWidgets.QFrame(main)
        self.frame_4.setGeometry(QtCore.QRect(10, 300, 250, 160))
        self.frame_4.setMinimumSize(QtCore.QSize(250, 160))
        self.frame_4.setMaximumSize(QtCore.QSize(250, 160))
        self.frame_4.setStyleSheet("background-color: rgb(0, 36, 66);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_10.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_10.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_4.addWidget(self.pushButton_10, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Tahoma\";")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 4, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_4.addWidget(self.pushButton_9, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_5 = QtWidgets.QFrame(main)
        self.frame_5.setGeometry(QtCore.QRect(270, 300, 520, 160))
        self.frame_5.setMinimumSize(QtCore.QSize(520, 160))
        self.frame_5.setMaximumSize(QtCore.QSize(520, 160))
        self.frame_5.setStyleSheet("background-color: rgb(0, 36, 66);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Tahoma\";")
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_11.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_11.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_11.setStyleSheet("font: 75 24pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 1, 0, 1, 1)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

        self.pushButton_2.clicked.connect(self.availableWindow)
        self.pushButton_11.clicked.connect(self.inventoryWindow)
        self.pushButton_4.clicked.connect(self.categoryWindow)
        self.pushButton_3.clicked.connect(self.outOfStockWindow)
        self.pushButton_6.clicked.connect(self.ReceivedHistoryWindow)
        self.pushButton_9.clicked.connect(self.TransactionHistoryWindow)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Furniture System"))
        self.pushButton_3.setText(_translate("main", "OP"))
        self.pushButton_4.setText(_translate("main", "C"))
        self.pushButton_2.setText(_translate("main", "AP"))
        self.label_4.setText(_translate("main", "Out of Stock"))
        self.label_5.setText(_translate("main", "Category"))
        self.label_6.setText(_translate("main", "Available"))
        self.label_2.setText(_translate("main", "Items"))
        self.label_3.setText(_translate("main", "Furniture Sales and Inventory System"))
        self.label_8.setText(_translate("main", "Balance"))
        self.label_10.setText(_translate("main", "Customers"))
        self.pushButton_5.setText(_translate("main", "CB"))
        self.pushButton_7.setText(_translate("main", "CI"))
        self.label_7.setText(_translate("main", "Customers"))
        self.label_9.setText(_translate("main", "Receive History"))
        self.label_11.setText(_translate("main", "Receive Items"))
        self.pushButton_6.setText(_translate("main", "RH"))
        self.pushButton_8.setText(_translate("main", "RI"))
        self.label_12.setText(_translate("main", "Receiving Items"))
        self.pushButton_10.setText(_translate("main", "PS"))
        self.label_15.setText(_translate("main", "Sales"))
        self.label_14.setText(_translate("main", "POS"))
        self.label_13.setText(_translate("main", "Transaction History"))
        self.pushButton_9.setText(_translate("main", "TH"))
        self.label_16.setText(_translate("main", "Reports & Alerts"))
        self.label_17.setText(_translate("main", "Item Inventory"))
        self.pushButton_11.setText(_translate("main", "IR"))


    def availableWindow(self):
        main.destroy()
        current_directory = os.path.dirname(os.path.abspath(__file__))
        script_path = os.path.join(current_directory, "Available_product.py")
        subprocess.run(["python", script_path])

    def inventoryWindow(self):
        main.destroy()
        current_directory = os.path.dirname(os.path.abspath(__file__))
        script_path = os.path.join(current_directory, "Inventory.py")
        subprocess.run(["python", script_path])

    def categoryWindow(self):
        main.destroy()
        current_directory = os.path.dirname(os.path.abspath(__file__))
        script_path = os.path.join(current_directory, "Product_category.py")
        subprocess.run(["python", script_path])

    def outOfStockWindow(self):
        main.destroy()
        current_directory = os.path.dirname(os.path.abspath(__file__))
        script_path = os.path.join(current_directory, "Out_of_stock.py")
        subprocess.run(["python", script_path])

    def ReceivedHistoryWindow(self):
        main.destroy()
        current_directory = os.path.dirname(os.path.abspath(__file__))
        script_path = os.path.join(current_directory, "Received_history.py")
        subprocess.run(["python", script_path])

    def TransactionHistoryWindow(self):
        main.destroy()
        current_directory = os.path.dirname(os.path.abspath(__file__))
        script_path = os.path.join(current_directory, "Transaction_history.py")
        subprocess.run(["python", script_path])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QFrame()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())
