# -*- coding: utf-8 -*-
import os
import subprocess

# Form implementation generated from reading ui file 'Product_category.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QTableWidgetItem

from Encryption import Encryption
from Product import Product


class Ui_ProductCategory(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 500)
        Frame.setMinimumSize(QtCore.QSize(800, 500))
        Frame.setMaximumSize(QtCore.QSize(800, 500))
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 781, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"Perpetua Titling MT\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton.setAcceptDrops(False)
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/Back_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setStyleSheet("background-image: url(image/BG.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Frame)
        self.tableWidget.setGeometry(QtCore.QRect(20, 130, 761, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(Frame)
        self.comboBox.setGeometry(QtCore.QRect(270, 70, 261, 41))
        self.comboBox.setObjectName("comboBox")
        self.label.raise_()
        self.label_3.raise_()
        self.tableWidget.raise_()
        self.pushButton.raise_()
        self.comboBox.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

        self.tableWidget.setFont(QFont("Tahoma", 12))
        self.comboBox.setFont(QFont("Tahoma", 12))
        self.pushButton.clicked.connect(self.backToMain)
        self.comboBox.currentIndexChanged.connect(lambda: self.display_table(self.get_selected_item()))

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Product Category"))
        self.label_3.setText(_translate("Frame", "Product Category"))

    item = []
    product_category = []

    def add_category(self, PC):
        for product in self.item:
            if product.getCategory() == PC:
                return
        self.product_category.append(PC)
    def add_item(self, data):
        self.item.append(data)

    def retrieve(self):

        try:
            with open(Encryption.decrypt("Ifyfgfxj&uwtizhyx.ycy"), "r") as reader:
                for line in reader:
                    line = Encryption.decrypt(line)
                    arr_line = line.split(" / ")
                    temp = Product()  # Create a new instance for each item
                    temp.setID(int(arr_line[0].strip()))
                    temp.setPrice(int(arr_line[1].strip()))
                    temp.setQuantity(int(arr_line[2].strip()))
                    temp.setProductName(arr_line[3].strip())
                    temp.setBrand(arr_line[4].strip())
                    temp.setDescription(arr_line[5].strip())
                    temp.setCategory(arr_line[6].strip())
                    self.add_category(temp.getCategory())
                    temp.setSupplier(arr_line[7].strip())
                    temp.setDate(arr_line[8].strip())
                    self.add_item(temp)
                    temp = Product()  # Create a new instance for each item
        except IOError as e:
            print("Error reading file:", e)
        finally:
            reader.close()

    def display_table(self, category):
        num_cols = 9

        # Filter items based on the category
        filtered_items = [item for item in self.item if item.getCategory() == category]
        num_rows = len(filtered_items)

        # Set the table dimensions
        self.tableWidget.setRowCount(num_rows)
        self.tableWidget.setColumnCount(num_cols)

        # Define the desired attribute names
        attribute_names = ["ID", "Price", "Quantity", "ProductName", "Brand", "Description", "Category", "Supplier",
                           "Date"]
        self.tableWidget.setHorizontalHeaderLabels(attribute_names)

        # Populate the table with data
        for row in range(num_rows):
            item = filtered_items[row]
            for col in range(num_cols):
                attribute_name = attribute_names[col]
                value = getattr(item, attribute_name)
                table_item = QTableWidgetItem(str(value))

                # Set the item flags to make it read-only
                table_item.setFlags(QtCore.Qt.ItemIsEnabled | QtCore.Qt.ItemIsSelectable)

                self.tableWidget.setItem(row, col, table_item)

        # Adjust column widths to maximize space
        # table_width = self.tableWidget.viewport().width()
        # column_width = int(table_width / num_cols)
        # for col in range(num_cols):
        #     self.tableWidget.setColumnWidth(col, column_width)

    def formWindowOpened(self):
        mod = QtGui.QStandardItemModel()
        for category in self.product_category:
            item = QtGui.QStandardItem(category)
            mod.appendRow(item)
        self.comboBox.setModel(mod)
        self.comboBox.setCurrentIndex(-1)

    def backToMain(self):
        ProductCategory.destroy()
        current_directory = os.path.dirname(os.path.abspath(__file__))
        script_path = os.path.join(current_directory, "main.py")
        subprocess.run(["python", script_path])

    def get_selected_item(self):
        selected_item = self.comboBox.currentText()
        return selected_item

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProductCategory = QtWidgets.QFrame()
    ui = Ui_ProductCategory()
    ui.setupUi(ProductCategory)
    ui.retrieve()
    ui.formWindowOpened()
    ProductCategory.show()
    sys.exit(app.exec_())
