# -*- coding: utf-8 -*-
import os
import subprocess

# Form implementation generated from reading ui file 'Receive_items.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Encryption import Encryption
from Product import Product


class Ui_ReceiveItems(object):
    def setupUi(self, ReceiveItems):
        ReceiveItems.setObjectName("ReceiveItems")
        ReceiveItems.setEnabled(True)
        ReceiveItems.resize(800, 500)
        ReceiveItems.setMinimumSize(QtCore.QSize(800, 500))
        ReceiveItems.setMaximumSize(QtCore.QSize(800, 500))
        ReceiveItems.setAutoFillBackground(True)
        self.tableWidget = QtWidgets.QTableWidget(ReceiveItems)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 781, 411))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet("background-color: rgb(0, 0, 191)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(ReceiveItems)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 781, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"Perpetua Titling MT\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.BACKBUTTON = QtWidgets.QPushButton(ReceiveItems)
        self.BACKBUTTON.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.BACKBUTTON.setMinimumSize(QtCore.QSize(50, 50))
        self.BACKBUTTON.setMaximumSize(QtCore.QSize(50, 50))
        self.BACKBUTTON.setAcceptDrops(False)
        self.BACKBUTTON.setAutoFillBackground(False)
        self.BACKBUTTON.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.BACKBUTTON.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/Back_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BACKBUTTON.setIcon(icon)
        self.BACKBUTTON.setIconSize(QtCore.QSize(50, 50))
        self.BACKBUTTON.setCheckable(False)
        self.BACKBUTTON.setObjectName("BACKBUTTON")
        self.label = QtWidgets.QLabel(ReceiveItems)
        self.label.setGeometry(QtCore.QRect(-1, -1, 1421, 561))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image: url(image/BG.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.PRODUCTTEXT = QtWidgets.QTextEdit(ReceiveItems)
        self.PRODUCTTEXT.setGeometry(QtCore.QRect(50, 120, 251, 31))
        self.PRODUCTTEXT.setObjectName("PRODUCTTEXT")
        self.PRODUCT = QtWidgets.QLabel(ReceiveItems)
        self.PRODUCT.setGeometry(QtCore.QRect(50, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.PRODUCT.setFont(font)
        self.PRODUCT.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Perpetua Titling MT\";")
        self.PRODUCT.setTextFormat(QtCore.Qt.RichText)
        self.PRODUCT.setAlignment(QtCore.Qt.AlignCenter)
        self.PRODUCT.setObjectName("PRODUCT")
        self.BRAND = QtWidgets.QLabel(ReceiveItems)
        self.BRAND.setGeometry(QtCore.QRect(470, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.BRAND.setFont(font)
        self.BRAND.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Perpetua Titling MT\";")
        self.BRAND.setTextFormat(QtCore.Qt.RichText)
        self.BRAND.setAlignment(QtCore.Qt.AlignCenter)
        self.BRAND.setObjectName("BRAND")
        self.UNITPRICE = QtWidgets.QLabel(ReceiveItems)
        self.UNITPRICE.setGeometry(QtCore.QRect(40, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.UNITPRICE.setFont(font)
        self.UNITPRICE.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Perpetua Titling MT\";")
        self.UNITPRICE.setTextFormat(QtCore.Qt.RichText)
        self.UNITPRICE.setAlignment(QtCore.Qt.AlignCenter)
        self.UNITPRICE.setObjectName("UNITPRICE")
        self.UPTEXT = QtWidgets.QTextEdit(ReceiveItems)
        self.UPTEXT.setGeometry(QtCore.QRect(50, 210, 251, 31))
        self.UPTEXT.setObjectName("UPTEXT")
        self.QUANTITY = QtWidgets.QLabel(ReceiveItems)
        self.QUANTITY.setGeometry(QtCore.QRect(480, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.QUANTITY.setFont(font)
        self.QUANTITY.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Perpetua Titling MT\";")
        self.QUANTITY.setTextFormat(QtCore.Qt.RichText)
        self.QUANTITY.setAlignment(QtCore.Qt.AlignCenter)
        self.QUANTITY.setObjectName("QUANTITY")
        self.DESCRIPTION = QtWidgets.QLabel(ReceiveItems)
        self.DESCRIPTION.setGeometry(QtCore.QRect(50, 270, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.DESCRIPTION.setFont(font)
        self.DESCRIPTION.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Perpetua Titling MT\";")
        self.DESCRIPTION.setTextFormat(QtCore.Qt.RichText)
        self.DESCRIPTION.setAlignment(QtCore.Qt.AlignCenter)
        self.DESCRIPTION.setObjectName("DESCRIPTION")
        self.DSCTEXT = QtWidgets.QTextEdit(ReceiveItems)
        self.DSCTEXT.setGeometry(QtCore.QRect(50, 300, 251, 31))
        self.DSCTEXT.setObjectName("DSCTEXT")
        self.BRANDTXT = QtWidgets.QTextEdit(ReceiveItems)
        self.BRANDTXT.setGeometry(QtCore.QRect(490, 120, 251, 31))
        self.BRANDTXT.setObjectName("BRANDTXT")
        self.QTYTEXT = QtWidgets.QTextEdit(ReceiveItems)
        self.QTYTEXT.setGeometry(QtCore.QRect(490, 210, 251, 31))
        self.QTYTEXT.setObjectName("QTYTEXT")
        self.SUPPLIER = QtWidgets.QLabel(ReceiveItems)
        self.SUPPLIER.setGeometry(QtCore.QRect(470, 270, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.SUPPLIER.setFont(font)
        self.SUPPLIER.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Perpetua Titling MT\";")
        self.SUPPLIER.setTextFormat(QtCore.Qt.RichText)
        self.SUPPLIER.setAlignment(QtCore.Qt.AlignCenter)
        self.SUPPLIER.setObjectName("SUPPLIER")
        self.SUPPTEXT = QtWidgets.QTextEdit(ReceiveItems)
        self.SUPPTEXT.setGeometry(QtCore.QRect(490, 300, 251, 31))
        self.SUPPTEXT.setObjectName("SUPPTEXT")
        self.CATEGORY = QtWidgets.QLabel(ReceiveItems)
        self.CATEGORY.setGeometry(QtCore.QRect(40, 360, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.CATEGORY.setFont(font)
        self.CATEGORY.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Perpetua Titling MT\";")
        self.CATEGORY.setTextFormat(QtCore.Qt.RichText)
        self.CATEGORY.setAlignment(QtCore.Qt.AlignCenter)
        self.CATEGORY.setObjectName("CATEGORY")
        self.CATEGCBOX = QtWidgets.QComboBox(ReceiveItems)
        self.CATEGCBOX.setGeometry(QtCore.QRect(50, 390, 221, 31))
        self.CATEGCBOX.setObjectName("CATEGCBOX")
        self.ADDEDIT_2 = QtWidgets.QLabel(ReceiveItems)
        self.ADDEDIT_2.setGeometry(QtCore.QRect(490, 360, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.ADDEDIT_2.setFont(font)
        self.ADDEDIT_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Perpetua Titling MT\";")
        self.ADDEDIT_2.setTextFormat(QtCore.Qt.RichText)
        self.ADDEDIT_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ADDEDIT_2.setObjectName("ADDEDIT_2")
        self.ADDEDIT = QtWidgets.QTextEdit(ReceiveItems)
        self.ADDEDIT.setGeometry(QtCore.QRect(490, 390, 151, 31))
        self.ADDEDIT.setObjectName("ADDEDIT")
        self.ADD = QtWidgets.QPushButton(ReceiveItems)
        self.ADD.setGeometry(QtCore.QRect(350, 420, 101, 41))
        self.ADD.setObjectName("ADD")
        self.ADD_2 = QtWidgets.QPushButton(ReceiveItems)
        self.ADD_2.setGeometry(QtCore.QRect(660, 390, 71, 31))
        self.ADD_2.setObjectName("ADD_2")
        self.ADD_3 = QtWidgets.QPushButton(ReceiveItems)
        self.ADD_3.setGeometry(QtCore.QRect(660, 430, 71, 31))
        self.ADD_3.setObjectName("ADD_3")
        self.label.raise_()
        self.tableWidget.raise_()
        self.label_3.raise_()
        self.BACKBUTTON.raise_()
        self.PRODUCTTEXT.raise_()
        self.PRODUCT.raise_()
        self.BRAND.raise_()
        self.UNITPRICE.raise_()
        self.UPTEXT.raise_()
        self.QUANTITY.raise_()
        self.DESCRIPTION.raise_()
        self.DSCTEXT.raise_()
        self.BRANDTXT.raise_()
        self.QTYTEXT.raise_()
        self.SUPPLIER.raise_()
        self.SUPPTEXT.raise_()
        self.CATEGORY.raise_()
        self.CATEGCBOX.raise_()
        self.ADDEDIT_2.raise_()
        self.ADDEDIT.raise_()
        self.ADD.raise_()
        self.ADD_2.raise_()
        self.ADD_3.raise_()

        self.retranslateUi(ReceiveItems)
        QtCore.QMetaObject.connectSlotsByName(ReceiveItems)

        #makes the combo box clicable (di naman ata kailangan)
        #self.CATEGCBOX.activated.connect(self.pressed)

        self.BACKBUTTON.clicked.connect(self.backToMain)

        #ADD_2 button to add text to combo box from text box
        self.ADD_2.clicked.connect(self.addTexttoComboBox)

        #ADD_3 button to edit text from combo box
        self.ADD_3.clicked.connect(self.editCombo)

        #COMBO BOX
        self.CATEGCBOX.addItems(["DINING ROOM", "LIVING ROOM", "BEDROOM"])

        #ADD BUTTON
        self.ADD.clicked.connect(self.AddItems)

    def retranslateUi(self, ReceiveItems):
        _translate = QtCore.QCoreApplication.translate
        ReceiveItems.setWindowTitle(_translate("ReceiveItems", "Receive Items"))
        self.label_3.setText(_translate("ReceiveItems", "receive items"))
        self.PRODUCT.setText(_translate("ReceiveItems", "PRODUCT"))
        self.BRAND.setText(_translate("ReceiveItems", "BRAND"))
        self.UNITPRICE.setText(_translate("ReceiveItems", "UNIT PRICE"))
        self.QUANTITY.setText(_translate("ReceiveItems", "quantity"))
        self.DESCRIPTION.setText(_translate("ReceiveItems", "DESCRIPTION"))
        self.SUPPLIER.setText(_translate("ReceiveItems", "SUPPLIER"))
        self.CATEGORY.setText(_translate("ReceiveItems", "CATEGORY"))
        self.ADDEDIT_2.setText(_translate("ReceiveItems", "ADD/EDIT CATEGORY"))
        self.ADD.setText(_translate("ReceiveItems", "ADD"))
        self.ADD_2.setText(_translate("ReceiveItems", "ADD"))
        self.ADD_3.setText(_translate("ReceiveItems", "EDIT"))

    item = []

    def add_item(self, data):
        self.item.append(data)

    def retrieve(self):
        file_path = "Database/received_product_history.txt"  # Replace with the actual file path

        try:
            with open(file_path, "r") as reader:
                for line in reader:
                    line = Encryption.decrypt(line)
                    arr_line = line.split(" / ")
                    temp = Product()  # Create a new instance for each item
                    temp.setID(int(arr_line[0].strip()))
                    temp.setPrice(int(arr_line[1].strip()))
                    temp.setQuantity(int(arr_line[2].strip()))
                    temp.setProductName(arr_line[3].strip())
                    temp.setBrand(arr_line[4].strip())
                    temp.setDescription(arr_line[5].strip())
                    temp.setCategory(arr_line[6].strip())
                    temp.setSupplier(arr_line[7].strip())
                    temp.setDate(arr_line[8].strip())
                    self.add_item(temp)
                    temp = Product()  # Create a new instance for each item
        except IOError as e:
            print("Error reading file:", e)

    def backToMain(self):
        ReceiveItems.destroy()
        current_directory = os.path.dirname(os.path.abspath(__file__))
        script_path = os.path.join(current_directory, "main.py")
        subprocess.run(["python", script_path])

    def pressed(self):
        print(self.CATEGCBOX.currentText())

    def addTexttoComboBox(self):
        text = self.ADDEDIT.toPlainText()

        self.CATEGCBOX.addItem(text)

    def editCombo(self):
        #gets the selected item from the cbox
        index = self.CATEGCBOX.currentIndex()
        #get new text from the text edit
        text = self.ADDEDIT.toPlainText()
        #sets the new text for the selected category
        self.CATEGCBOX.setItemText(index, text)

    def AddItems(self):
        prod_text = self.PRODUCTTEXT.toPlainText()
        brand_text = self.BRANDTXT.toPlainText()
        up_text = self.UPTEXT.toPlainText()
        qty_text = self.QTYTEXT.toPlainText()
        desc_text = self.DSCTEXT.toPlainText()
        supp_text = self.SUPPTEXT.toPlainText()

        if not prod_text or not brand_text or not up_text or not qty_text or not desc_text or not supp_text:
            print(self, 'Warning', 'Text Editors cannot be empty!')
        else:
            print(self, 'Information', 'Input Succesful')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReceiveItems = QtWidgets.QFrame()
    ui = Ui_ReceiveItems()
    ui.setupUi(ReceiveItems)
    ui.retrieve()
    ReceiveItems.show()
    sys.exit(app.exec_())
